services:
  redis:
    image: redis:8.2.1
    ports:
      - "6386:6379"
    networks:
      - default

  rabbit:
    image: rabbitmq:4-management
    ports:
      - "5676:5672"
      - "15676:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "carbon-relay"
      RABBITMQ_DEFAULT_PASS: "carbon-relay"
      RABBITMQ_DEFAULT_VHOST: "carbon-relay"
    networks:
      - default

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=Bql796q98CKdUrF
      - POSTGRES_DB=carbon_relay
      - POSTGRES_USER=carbon_relay_user
    ports:
      - "3311:5432"
    volumes:
      - postgres-db-carbon-relay:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

  kafka-carbon-relay:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "29061:29061"
    environment:
      CLUSTER_ID: "carbon-relay-dev-cluster"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29061
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-carbon-relay:9092,EXTERNAL://localhost:29061
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-carbon-relay:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data-carbon-relay:/var/lib/kafka/data
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
      - default

  kafka-carbon-relay-rest:
    image: confluentinc/cp-kafka-rest:7.9.0-1-ubi8
    hostname: kafka-carbon-relay-rest
    depends_on:
      kafka-carbon-relay:
        condition: service_healthy
    environment:
      KAFKA_REST_HOST_NAME: "kafka-carbon-relay-rest"
      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka-carbon-relay:9092"
      KAFKA_REST_AUTHENTICATION_METHOD: BASIC
      KAFKA_REST_AUTHENTICATION_REALM: KafkaRest
      KAFKA_REST_AUTHENTICATION_ROLES: rest
      KAFKAREST_OPTS: -Djava.security.auth.login.config=/etc/kafka-rest/rest-jaas.properties
    volumes:
      - ./kafka-rest/password.properties:/password.properties
      - ./kafka-rest/rest-jaas.properties:/etc/kafka-rest/rest-jaas.properties
    networks:
      - default

  kafka-ui:
    image: kafbat/kafka-ui:latest
    ports:
      - "9026:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "carbon-relay-dev"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-carbon-relay:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    depends_on:
      kafka-carbon-relay:
        condition: service_healthy

  kafka-seeder:
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      kafka-carbon-relay:
        condition: service_healthy
    volumes:
      - ./kafka-seeder/seed-config-kafka.sh:/usr/local/bin/seed-config-kafka.sh
      - ./kafka-seeder/messages.json:/usr/local/bin/messages.json
      - ./kafka-seeder/csv-messages:/usr/local/bin/csv-messages
    environment:
      KAFKA_BROKER: kafka-carbon-relay:9092
    entrypoint: [ "sh", "-c", "sh /usr/local/bin/seed-config-kafka.sh" ]
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y jq &&
        sh /usr/local/bin/seed-config-kafka.sh
      "
    networks:
      - default





volumes:
  kafka-data-carbon-relay:
  postgres-db-carbon-relay:
